# Site settings
title: Halleyin
legal_title: Halleyin Software Consultancy LTD
email: info@halleyin.com
description: "Software and IT Consultancy Services"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/company/halleyin-software-consultancy/
  - title: envelope
    url: mailto:info@halleyin.com

# Postal address (add as many lines as necessary)
address:
  - line: Suite 5336, Unit 3A, 34-35 Hatton Garden, Holborn, London, EC1N 8DX

# Build settings
markdown: kramdown
permalink: pretty